### ISSUE TITLE
使用当中出现的问题

### ISSUE THREAD

**Issue by lovelself** [Meowya/JCQ-CoolQ#1]
首先很感谢提供了java SDK的支持，让更多java开发者也能参与到酷Q的插件开发当中

在使用当中，我发现了一些小小的问题和给予一些建议：
1、在现有的API中，所有的实体Entity类都没有实现序列化接口，导致在使用当中，经常性报类转换异常。原本使用steam流处理中的特性即可完成的，现在需要大量的编码去处理，实在不划算，还望您补充一下；
2、在现有的消息获取工具当中，希望加入一个过滤掉所有的CQCode，仅返回普通的消息文本的方法，不知道能否实现；

非常感谢！

**Comment by Sobte** [comment]
相关功能已经更新
1、实体类均于实现序列化接口
2、提供了CoolQMsg、CoolQCode，分别管理酷Q码和普通消息的处理
