### ISSUE TITLE
pom文件问题

### ISSUE THREAD

**Issue by sddcg-Jam** [Meowya/JCQ-CoolQ#2]
<parent>
        <artifactId>jcq-parent</artifactId>
        <groupId>org.meowy.cqp</groupId>
        <version>1.2.8</version>
    </parent>

以上信息maven中找不到

**Comment by Sobte** [comment]
此问题出现于测试但未发布的版、现已发布新版
```
    <groupId>org.meowy.cqp</groupId>
    <artifactId>jcq-coolq</artifactId>
    <version>1.3.0</version>
```
